# Generated by Django 5.2.17 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="numero_patrimonio",
            field=models.CharField(
                error_messages={
                    "unique": "Já existe um equipamento cadastrado com este número de patrimônio."
                },
                max_length=50,
                unique=True,
                verbose_name="número de patrimônio",
            ),
        ),
    ]
