class AcaoAuditoria:
    ACESSO_NEGADO = "ACESSO_NEGADO"
    LOGIN_REALIZADO = "LOGIN_REALIZADO"
    LOGIN_FALHOU = "LOGIN_FALHOU"
    LOGOUT_REALIZADO = "LOGOUT_REALIZADO"
    INVENTARIO_CONSULTADO = "INVENTARIO_CONSULTADO"
    MODELO_CSV_BAIXADO = "MODELO_CSV_BAIXADO"
    EQUIPAMENTO_CADASTRADO = "EQUIPAMENTO_CADASTRADO"
    EQUIPAMENTOS_IMPORTADOS = "EQUIPAMENTOS_IMPORTADOS"
    EQUIPAMENTO_EXCLUIDO = "EQUIPAMENTO_EXCLUIDO"
    EQUIPAMENTO_INATIVADO = "EQUIPAMENTO_INATIVADO"
    USUARIO_CADASTRADO = "USUARIO_CADASTRADO"
    DOCUMENTOS_LEGAIS_ACEITOS = "DOCUMENTOS_LEGAIS_ACEITOS"


def rotulo_acao(acao):
    return acao.replace("_", " ").capitalize()
