# Generated by Django 5.2.17 on 2026-09-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acao", models.CharField(max_length=100)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("SUCESSO", "Sucesso"),
                            ("FALHA", "Falha"),
                            ("ACESSO_NEGADO", "Acesso negado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("entidade", models.CharField(blank=True, max_length=100)),
                ("entidade_id", models.CharField(blank=True, max_length=100)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoria",
                "verbose_name_plural": "registros de auditoria",
                "ordering": ["-data_hora", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("acao", ""), _negated=True),
                        name="auditoria_acao_nao_vazia",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("resultado__in", ["SUCESSO", "FALHA", "ACESSO_NEGADO"])
                        ),
                        name="auditoria_resultado_valido",
                    ),
                ],
            },
        ),
    ]
