# Generated by Django 5.2.17 on 2026-10-06 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0005_tipo_equipamento'),
        ('movimentacoes', '0004_movimentacao_lote_retirada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do problema')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, choices=[('REPARADO', 'Reparado'), ('SEM_REPARO', 'Sem possibilidade de reparo')], max_length=20)),
                ('descricao_solucao', models.TextField(blank=True, verbose_name='Solução ou conclusão da análise')),
                ('aberto_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes_abertas', to=settings.AUTH_USER_MODEL)),
                ('concluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes_concluidas', to=settings.AUTH_USER_MODEL)),
                ('devolucao_origem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manutencao', to='movimentacoes.movimentacao')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='inventario.equipamento')),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes_iniciadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'manutenção',
                'verbose_name_plural': 'manutenções',
                'ordering': ['-data_abertura', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado__in', ['PENDENTE', 'EM_ANDAMENTO'])), fields=('equipamento',), name='manutencao_aberta_unica_equip'), models.CheckConstraint(condition=models.Q(('descricao_problema', ''), _negated=True), name='manutencao_exige_problema'), models.CheckConstraint(condition=models.Q(models.Q(('data_inicio__isnull', True), ('estado', 'PENDENTE'), ('iniciado_por__isnull', True)), models.Q(('data_inicio__isnull', False), ('estado__in', ['EM_ANDAMENTO', 'CONCLUIDA']), ('iniciado_por__isnull', False)), _connector='OR'), name='manutencao_inicio_coerente'), models.CheckConstraint(condition=models.Q(models.Q(('concluido_por__isnull', True), ('data_conclusao__isnull', True), ('descricao_solucao', ''), ('estado__in', ['PENDENTE', 'EM_ANDAMENTO']), ('resultado', '')), models.Q(('concluido_por__isnull', False), ('data_conclusao__isnull', False), ('estado', 'CONCLUIDA'), ('resultado__in', ['REPARADO', 'SEM_REPARO']), models.Q(('descricao_solucao', ''), _negated=True)), _connector='OR'), name='manutencao_conclusao_coerente'), models.CheckConstraint(condition=models.Q(('data_inicio__isnull', True), ('data_inicio__gte', models.F('data_abertura')), _connector='OR'), name='manutencao_inicio_apos_abertura'), models.CheckConstraint(condition=models.Q(('data_conclusao__isnull', True), ('data_conclusao__gte', models.F('data_inicio')), _connector='OR'), name='manutencao_conclusao_apos_inicio')],
            },
        ),
    ]
