# Generated by Django 5.2.17 on 2026-09-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AceiteDocumentosLegais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "versao_termos",
                    models.CharField(
                        max_length=20,
                        verbose_name="versão dos Termos de Uso",
                    ),
                ),
                (
                    "versao_privacidade",
                    models.CharField(
                        max_length=20,
                        verbose_name="versão da Política de Privacidade",
                    ),
                ),
                (
                    "aceito_em",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="aceito em",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aceites_documentos_legais",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "aceite de documentos legais",
                "verbose_name_plural": "aceites de documentos legais",
                "ordering": ["-aceito_em", "-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "usuario",
                            "versao_termos",
                            "versao_privacidade",
                        ),
                        name="legal_aceite_unico_por_versoes",
                    ),
                ],
            },
        ),
    ]
