# Generated by Django 5.2.17 on 2026-09-23 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
        ('reservas', '0004_alter_reserva_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('RETIRADA', 'Retirada'), ('DEVOLUCAO', 'Devolução')], max_length=20),
        ),
    ]
