# Generated by Django 5.2.17 on 2026-10-03 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_tipo_equipamento'),
        ('movimentacoes', '0002_movimentacao_reserva_alter_movimentacao_tipo'),
        ('reservas', '0004_alter_reserva_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'DEVOLUCAO')), fields=('retirada_origem',), name='mov_devolucao_unica_origem'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'DEVOLUCAO'), _negated=True), ('retirada_origem__isnull', False), _connector='OR'), name='mov_devolucao_exige_origem'),
        ),
    ]
