# Generated by Django 5.2.17 on 2026-10-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0003_movimentacao_mov_devolucao_unica_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='lote_retirada',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
