# Generated by Django 5.2.17 on 2026-10-06 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0004_movimentacao_lote_retirada'),
        ('pedagogico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilizacaoPedagogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.atividadepedagogica')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.disciplina')),
                ('movimentacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='utilizacao_pedagogica', to='movimentacoes.movimentacao')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilizacoes_pedagogicas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.turma')),
            ],
            options={
                'verbose_name': 'utilização pedagógica',
                'verbose_name_plural': 'utilizações pedagógicas',
                'ordering': ['-data_criacao', '-pk'],
                'default_permissions': ('view', 'add', 'change'),
            },
        ),
    ]
