# Generated by Django 5.2.17 on 2026-09-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventario", "0004_alter_equipamento_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField(verbose_name="início")),
                ("fim", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ATIVA", "Ativa"), ("CANCELADA", "Cancelada")],
                        default="ATIVA",
                        max_length=20,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="inventario.equipamento",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "reserva",
                "verbose_name_plural": "reservas",
                "ordering": ["-inicio", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["equipamento", "inicio", "fim"],
                        name="reserva_equip_periodo_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(fim__gt=models.F("inicio")),
                        name="reserva_fim_posterior_inicio",
                    )
                ],
            },
        ),
    ]
